### PR TITLE
feat: add middleware to options and peer argument to proxyMsg event.

### PR DESCRIPTION
**Pull request by oronm**
Hi Olli, great project, thanks for putting it out there. I used the node udp proxy on a project of mine and it saved me a lot of time. 

I found the need to add a middleware to the proxy, so I'd be able to manipulate the messages going in and out. Been running this for a few weeks and it works very well. 

Hope you'll find my PR useful and merge it.

Best,
-Oron

### CODE REVIEW

**Comment by gildean** [comment]
Hi,
Looks pretty good, I'd imagine it could be useful.
Could you remove the unnecessary changes to the readme above this line https://github.com/gildean/node-udp-proxy/pull/7/files#diff-04c6e90faac2675aa89e2176d2eec7d8R143 and also add a newline to the end of the js-file.

**Comment by oronm** [comment]
Sorry for the mess in the README file, used a different editor now it looks better now. 
Also added a new line to the end of index.js

**Comment by oronm** [comment]
@gildean hoping you'll get a chance to merge that
thx!

**Comment by oronm** [comment]
One last ping here @gildean

**Comment by gildean** [comment]
Sorry. been too busy. I'll merge this as soon as I'm in front of my computer.

**Pull request merged**
